### ISSUE TITLE
gesticulator-requirements

### ISSUE THREAD

**Issue by catherine-qian** [Svito-zar/gesticulator#13]
Thanks for the amazing work!
the package specified in requirements.txt under 'gesticulator' has some conflicts. Could you please double-check the requirements and update the file?

**Comment by Svito-zar** [comment]
Thanks for flaging this @catherine-qian .

I could reproduce the error:
```
(gest_env) tarask@tarask-lap:~/Documents/Code/repr/gesticulator$ pip install -r gesticulator/requirements.txt 
Collecting absl-py==0.9.0
  Using cached absl-py-0.9.0.tar.gz (104 kB)
Collecting audioread==2.1.8
  Using cached audioread-2.1.8.tar.gz (21 kB)
Collecting bert-embedding==1.0.1
  Using cached bert_embedding-1.0.1-py3-none-any.whl (13 kB)
INFO: pip is looking at multiple versions of audioread to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of absl-py to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r gesticulator/requirements.txt (line 3) and numpy==1.18.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.18.2
    bert-embedding 1.0.1 depends on numpy==1.14.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

We will fix the conflict as soon as possible

**Comment by Svito-zar** [comment]
It seems that `bert-emdedding` is not maintained any longer and is causing this dependency conflict:
https://pypi.org/project/bert-embedding/

@nagyrajmund , how do you think, should we switch to the implementation from HuggingFace?
https://huggingface.co/transformers/model_doc/bert.html

**Comment by nagyrajmund** [comment]
@Svito-zar: It's a good idea, I think we can transition to HuggingFace's implementation in the upcoming weeks, but we have to make sure it produces the exact same outputs.

@catherine-qian: This is caused by a recent change to pip's dependency resolver introduced in version 20.3. I propose two temporary workarounds for now:

OPTION 1: Downgrade the pip version (`pip install pip==20.2`), then install the requirements again. Some errors will still appear about conflicting numpy versions (as noted in in the README), but the packages should be installed successfully.

OPTION 2: Alternatively, if you want to keep your pip version, then remove `mxnet`, `bert-embedding` and `numpy` from `requirements.txt`, and do the following:
```
pip install -r requirements.txt
pip install bert-embedding==1.0.1
pip install numpy==1.18.2
```

Let me know if you run into any issues.

**Comment by catherine-qian** [comment]
@nagyrajmund thanks! 
I tried option 2 and now all the packages are installed
