### ISSUE TITLE
evaluation metric 

### ISSUE THREAD

**Issue by catherine-qian** [Svito-zar/gesticulator#15]
For the evaluation metric, e.g. Table 3 and Fig. 4, what does the value mean?
Does higher/lower value correspond to better results? Or if the value is close to the ground truth=> better result

**Comment by Svito-zar** [comment]
Closer to the ground truth means better results

**Comment by catherine-qian** [comment]
thanks for the update

**Comment by catherine-qian** [comment]
![image](https://user-images.githubusercontent.com/8257740/101912051-344a1600-3bfc-11eb-99b8-30ec08cd888b.png)
so the number with red surroundings correspond to the best result?

**Comment by ghenter** [comment]
Note that the figures and tables mentioned here contain objective metrics, which generally do not correlate much with actual subjective quality as rated by a human. See [our GENEA Challenge 2020 preprint](https://doi.org/10.5281/zenodo.4094696) for clear examples of this disparity.

In other words, the "best numbers" does not equate to the best motion. That's why we always perform user studies, and base our final conclusions on those.

**Comment by Svito-zar** [comment]
Yes, you understood it correctly, @catherine-qian .
But as @ghenter noted - unfortunately, objective metrics are not well correlated with subjective metrics.
Also, note that RMSE has a very high standard deviation indicating extreme variance.
