### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by birdflies** [Svito-zar/gesticulator#38]
Dear,
When I use my own data to train the models.
I encountered the following error:
```
ERROR: GesticulatorModel.forward() returned None
Possible causes: corrupt dataset or a problem with the environment.
```
Do you think what  is the reason and How to solve it?
In forward function, why set "motion_seq = None"  every time ?

**Comment by Svito-zar** [comment]
`motion_seq` is set to `None` in the `forward` function only in the validation step, but not during the training step.
Since motion is the correct output it should not be available when we evaluate the model.

As for the issue you are getting - I am not sure why you have it and it's hard to say. I would suggest you to debug the code and see why the model does not return anything.

**Comment by birdflies** [comment]
Thanks~
