### ISSUE TITLE
FiLM algorithm, why (alpha + 1)?

### ISSUE THREAD

**Issue by kelvinqin** [Svito-zar/gesticulator#5]
Thanks for your work, which is great! When I reading ur code, a question comes to my mind:
In my understanding, the correct equation should be, output = nn_layer * (alpha) + beta, why you add 1 in your implementation,

Thanks

**Comment by Svito-zar** [comment]
Hi, @kelvinqin . Thank you for your question.

I assume you refer to this line in the `model.py` file: 
https://github.com/Svito-zar/gesticulator/blob/master/gesticulator/model/model.py#L398 

We used `nn_layer * (alpha+1) + beta` in order to have no transformation on the conditioning when we start the training.
To do so we initialized the weights of the final conditioning layer `self.conditioning_1` with all zeros. When we start training, the output of the FiLM network that predicts alpha and beta is close to zero. This simple trick means that the network behaves like alpha is close to one instead, so the FiLM conditioning is initialized to pass things through mostly unchanged instead of multiplying them by zero.

Did it answer your question?

**Comment by kelvinqin** [comment]
Dear Svito-zar,
Yes. That is my question. Many many  thanks for your answer, very insightful.

But just curious, that you already have a parameter named "use_conditioning", which can control FiLM just pass the input signal through in the first several epochs (7 I guess?) ---
https://github.com/Svito-zar/gesticulator/blob/master/gesticulator/model/model.py#L444

In this sense, are (alpha +1) and "use_conditioning" control a little redundant with each other please?

Best regards,
Kelvin

**Comment by Svito-zar** [comment]
Yes, you are absolutely right, Kelvin, that there is no conditioning at all for the first 7 epochs. But the special scheme for the FiLM is not redundant, It is ensuring that the transition happens smoothly. 

Since `alpha` and `beta` are generated by a neural network and can in general attain any values, without proper initialization after 7 epochs the signal (values which are passed into a neural network) would suddenly change a lot at the conditioning step, which could destabilize the training.

Our special treatment for FiLM initialization and usage is there to make sure that when conditioning "unfreezes" the network behavior change slowly. For the first batch, FiLM would do nothing as before and then it would slowly update its parameters moving away from the identity function.

Does it make sense to you?

**Comment by kelvinqin** [comment]
Dear Svito-zar,

Thanks a lot for your nice sharing, I fully understood that now, great job,

I have been tried very hard to repeat your great work using my own way (I am using the regular pytorch framework because I am not familiar with the great tool you are using, pytorch-lightning) :-(

**One specific question**: In your script, I can not find how many epochs you trained, can you suggest me how many epochs I should train? Thanks a lot. As you suggested in your paper, I am also using 64 batchsize, 1e-4 LR, about n_prev_poses, I am using 5 instead of 3 (not sure if it will cause overpower from condition, will check)

**Last question**: now I fully understand the rational of the trick (alpha + 1) which is for smooth model training, my question is, in decoding (or inference) phase, will FiLM still using (alpha +1), or use (alpha)?
 
Thanks again and have a nice day,
Kelvin

**Comment by Svito-zar** [comment]
Hi Kelvin,

1. About the number of epochs: I trained the model until convergence which always happened before 300 epochs. So I stop it after 300 epochs. Less should be fine. In my implementation it would take me some 20-40s per epoch on a GPU. So the whole training lasts just a couple of hours.
Remember the special training scheme we used, which I describe in details in the paper.

2. As for the FiLM in inference phase (test time) - the FiLM formulas do not change. It was trained with `alpha +1` which lies in the interval [0, 2] (because tanh activation lies in [-1,1]), so it would not work well with the `alpha` which lie in the interval [-1,1]. 

If I answered your question - please close this issue.
If you have other questions - please open new issues.

Best regards,
Taras

**Comment by kelvinqin** [comment]
Dear Taras,
Thanks a lot, yes, you answered all my question, thanks again for your work,
Kelvin

**Comment by kelvinqin** [comment]
Dear Taras,
Thanks a lot, yes, you answered all my question, thanks again for your work,
Kelvin
